---
# task/configure file for deploy_adguard
- name: "Copy gitea-runnner.service file"
  ansible.builtin.template:
    src: "gitea-runnner.service.j2"
    dest: "/etc/systemd/system/gitea-runnner.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemctl-daemon-reload

- name: "Configure docker-compose deployment"
  block:
    - name: "Copy docker-compose.yml template"
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "{{ deploy_gitea_runner_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: '0600'
      notify:
        - systemctl-enable-gitea-runnner
        - systemctl-restart-gitea-runnner

- name: "Copy config.yaml"
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ deploy_gitea_runner_directory }}/config.yaml"
    owner: root
    group: root
    mode: '0600'
  when: deploy_gitea_runner_config != {}
  notify:
    - systemctl-restart-gitea-runnner
