---
# task/main file for deploy_gitea_runner
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml
