---
# handlers file for deploy_adguard
- name: "Reload systemd file"
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: "systemctl-daemon-reload"

- name: "Enable gitea-runner service"
  ansible.builtin.service:
    name: gitea-runner
    enabled: true
  become: true
  listen: "systemctl-enable-gitea-runner"

- name: "Start gitea-runner service"
  ansible.builtin.service:
    name: gitea-runner
    state: restarted
  listen: "systemctl-restart-gitea-runner"
  throttle: 1
  when: deploy_gitea_runner_start_service
  become: true
