---
# handlers file for deploy_adguard
- name: "Reload systemd file"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemctl-daemon-reload"

- name: "Enable gitea-actions-runnner service"
  ansible.builtin.service:
    name: gitea-actions-runnner
    enabled: true
  listen: "systemctl-enable-gitea-actions-runnner"

- name: "Start gitea-actions-runnner service"
  ansible.builtin.service:
    name: gitea-actions-runnner
    state: restarted
  listen: "systemctl-restart-gitea-actions-runnner"
  throttle: 1
  when: deploy_gitea_runner_start_service
